# Generated by Django 4.0.5 on 2023-01-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Ism familiyasi')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Telefon raqami')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Faolmas'), ('PAUSED', 'Pauza')], max_length=50, null=True)),
                ('debt', models.BooleanField(default=True, verbose_name='Qarzi bor')),
                ('created', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tarif nomi')),
                ('days', models.PositiveIntegerField(verbose_name='Kunlari(bir oyda nech kun)')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('info', models.TextField(blank=True, verbose_name="Tarif xaqida ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_days', models.PositiveIntegerField(verbose_name='kelishi kerak bo`ldan kunlar')),
                ('payment', models.PositiveIntegerField(verbose_name='to`lashi kerak bo`lgan summa')),
                ('created', models.DateField(auto_now_add=True)),
                ('came', models.PositiveIntegerField(default=0, verbose_name='kelgan kunlari')),
                ('payed', models.BooleanField(default=False, verbose_name='To`landi')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='months', to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('money', models.IntegerField(verbose_name='Puli')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.month')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(default=0)),
                ('info', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='main.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('came', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.month')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='coming_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_clients', to='main.comingtype'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
