# Generated by Django 3.2.9 on 2022-12-10 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tarif nomi')),
                ('days', models.PositiveIntegerField(verbose_name='Kunlari(bir oyda nech kun)')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('info', models.TextField(blank=True, verbose_name="Tarif xaqida ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism familiyasi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('debt', models.BooleanField(default=False, verbose_name='Qarzi bor')),
                ('created', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('coming_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_clients', to='main.comingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
