# Generated by Django 4.1.4 on 2022-12-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('PAUSED', 'paused')], max_length=50, null=True),
        ),
    ]
