# Generated by Django 4.0.5 on 2023-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='chegirma'),
        ),
    ]
