# Generated by Django 4.0.5 on 2023-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_month_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='discount',
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='chegirma'),
        ),
    ]
