# Generated by Django 3.2.9 on 2022-12-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Oy nomi')),
                ('days', models.PositiveIntegerField(verbose_name='Oy kunlari')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_days', models.PositiveIntegerField(verbose_name='kelishi kerak bo`ldan kunlar')),
                ('payment', models.PositiveIntegerField(verbose_name='to`lashi kerak bo`lgan summa')),
                ('came', models.PositiveIntegerField(verbose_name='kelgan kunlari')),
                ('payed', models.BooleanField(default=False, verbose_name='To`landi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='main.client')),
                ('month_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.monthname', verbose_name='Oy')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('came', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.month')),
            ],
        ),
    ]
