# Generated by Django 3.2.9 on 2022-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_month_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthname',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Oy raqami'),
            preserve_default=False,
        ),
    ]
