# Generated by Django 3.2.9 on 2022-12-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20221215_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='came',
            field=models.PositiveIntegerField(default=0, verbose_name='kelgan kunlari'),
        ),
    ]
